### ISSUE TITLE
No such module 'InputAssistant'

### ISSUE THREAD

**Issue by xiongxiongjiang** [ColdGrub1384/Pisth#10]
after run ./setup.sh Xcode show "No such module 'InputAssistant'"

**Comment by ColdGrub1384** [comment]
Do you opened `Pisth.xcworkspace`? And also, if you see the `InputAssistant` folder inside the repo, is it empty? If `InputAssistant` is empty, there should have be an error while cloning it. Did you tried to build Pisth even if the error is shown? Sometimes Xcode shows errors but it works after compiling.

**Comment by xiongxiongjiang** [comment]
Thank you. Oh I know what's wrong. I shouldn't download the zip directly because it will lose some file. I use "git clone" then it works.

**Comment by ColdGrub1384** [comment]
I see. InputAssistant is downloaded with git submodule. When the zip file is downloaded, the .git directory is gone so git cannot install InputAssistant.
