### ISSUE TITLE
Terminal keyboard is set to capitalize

### ISSUE THREAD

**Issue by onfoot** [ColdGrub1384/Pisth#13]
It's incredibly annoying to have to disable Shift on every line in SSH. What's the rationale for that keyboard setting?

If you prefer, I can read through sources and create a PR with the fix.

Thanks!

**Comment by ColdGrub1384** [comment]
Thank you! It doesn't happen on my devices, but, I haven't disabled auto capitalization, so, this should fix that: 428170b2acaa575b01f5e7bcf8aadd7b6a989763

**Comment by onfoot** [comment]
Thanks! I'm sorry if I sounded entitled or like implying you did that on purpose. 😊 BUT GIMME AN APP STORE RELEASE WITH A FIX! 😃 

But seriously, are you releasing an update any time soon?

**Comment by ColdGrub1384** [comment]
Yes, I submitted an update and Apple has to review it, so it will be released soon. The bug doesn’t happen on my devices, so I’m not 100% sure this will be fixed.

**Comment by onfoot** [comment]
Got the update yesterday, and capitalization is off, so thanks again! :)
