### ISSUE TITLE
macOS version

### ISSUE THREAD

**Issue by georgesnow** [ColdGrub1384/Pisth#14]
ever think of extending support to macOS for SSH and SFTP? I haven't tried the iOS app, but there aren't really any macOS SSH apps that have both SFTP (GUI) and SSH.

**Comment by ColdGrub1384** [comment]
I will port the app to macOS after WWDC19. Apple is releasing something to code iOS apps and with the same code, build them for the Mac. It’s already in macOS 10.14, but privately. https://www.imore.com/marzipan

**Comment by georgesnow** [comment]
haha, that's funny. i thought that might be the case. i will keep an eye out. thanks
