### ISSUE TITLE
Connecting via ssh key fails with password blank

### ISSUE THREAD

**Issue by ksotin** [ColdGrub1384/Pisth#15]
I cannot seem to pass the authentication via keys when I leave the password blank. The keys are correct, which was tested on another client.

**Comment by ColdGrub1384** [comment]
Do the private key have a passphrase? If yes, you should put the SSH passphrase in password field.

**Comment by ksotin** [comment]
@ColdGrub1384 No, no passphrase.

**Comment by ColdGrub1384** [comment]
How did you generated the SSH keys? So I can try to reproduce the issue.

**Comment by ColdGrub1384** [comment]
As the keys work on other SSH clients, that may be an issue of [`libssh2`](https://www.libssh2.org).

**Comment by ksotin** [comment]
@ColdGrub1384 I generated the keys using ssh-keygen command on my Mac.

**Comment by ColdGrub1384** [comment]
Ok. I think I finally found the issue. I have to update `libssh2` to a version that supports new OpenSSH keys format. https://github.com/libssh2/libssh2/issues/68

**Comment by ksotin** [comment]
Thanks for your effort!

**Comment by ColdGrub1384** [comment]
I just fixed it! The problem was that macOS was generating SSH keys in a "new" format unsupported by the library I was using, but I just had to update it. I will release an update today.

**Comment by ColdGrub1384** [comment]
The issue is now fixed on the App Store version. Thank you for reporting.
