### ISSUE TITLE
Insert button and screen size

### ISSUE THREAD

**Issue by MoNTE48** [ColdGrub1384/Pisth#16]
Friend, where's the Insert?
I am a simple person and use 'vim".  How do I start typing?

**Comment by MoNTE48** [comment]
Ok, another problem. iPhone Xr.
htop. Pisth
![BE68E05F-9DDA-497C-85E2-557E4231EA78](https://user-images.githubusercontent.com/6764600/58762062-cecb9280-854b-11e9-8af5-17c5265f5991.png)
htop. Termius
![757DA6E6-1C92-4F98-B4B4-025DE2378AFB](https://user-images.githubusercontent.com/6764600/58762081-1520f180-854c-11e9-9b08-a429ccfc0708.png)

**Comment by ColdGrub1384** [comment]
Try to tap in the terminal and you should be able to type.

**Comment by ColdGrub1384** [comment]
If you type `i` you should be able to type in `vim`.

**Comment by ColdGrub1384** [comment]
Does the `htop` issue happen all time or just in some cases? Also, does it happen only with `htop` or also with other programs, for example `nano`?

**Comment by MoNTE48** [comment]
Hmm, how many years I use Linux on servers and did not know it! Ok, the question is removed. Next.
It seems that the terminal area does not occupy the entire screen. You also have some problem with scaling. This can be seen if I open an application with a background, for example htop.

**Comment by ColdGrub1384** [comment]
I will check that, but I’m not sure I will fix it. The terminal is an HTML page and the problem seems to be something with the library that I use to display the terminal.

**Comment by ColdGrub1384** [comment]
If you change the font size from settings, more information will be displayed.

**Comment by MoNTE48** [comment]
I do not agree with you.  The HTML page is simply not stretched to full screen.  Optimization issue for iPhone XR.
![29F12E0B-D015-4111-BC02-94AF9BD7C632](https://user-images.githubusercontent.com/6764600/58765481-ed458400-8573-11e9-9e25-fea6063d941a.jpeg)

**Comment by ColdGrub1384** [comment]
![1DD8C238-B810-4268-B04F-860CF056139F](https://user-images.githubusercontent.com/19255527/58765857-40eca900-8545-11e9-9644-7c3656025911.jpeg)

This also happen on iPhone 7. The page is stretched but there is a margin.

**Comment by MoNTE48** [comment]
I hope that you can find a solution. If the terminal is an HTML page, simply revise the code of the webview object you are using. Unfortunately, I know more about Java Android, so I can not help you.
