### ISSUE TITLE
Error opening session!

### ISSUE THREAD

**Issue by willpuckett** [ColdGrub1384/Pisth#24]
Made a new set of keys and installed to *remotehost* with `ssh-copy-id`, which returned exit status of 0. 

Copied keys into pisth public and private key import, and got:

```Error opening session!
Unable to authenticate, check
For username and password.
```

Also made a text version of the keys and dropped it into the pisth directory, then imported to host config, with same error.

Also tried an older set of RSA keys with same error.

Both keys are in my known_hosts file, and both work successfully to login to ssh from other apps.

Neither key has a pass phrase, and I have tried both leaving the password field blank, and filling it in with my password. The ssh server does not allow password logins.

Thoughts?

**Comment by willpuckett** [comment]
It looks like this was due to my .bashrc file having outputting to stdout.

Thanks!

**Comment by willpuckett** [comment]
Sorry I spoke too soon. Removing output fixed sftp login from another machine, but it still does not work in pisth. Reopening.

**Comment by janprzy** [comment]
Same here, Pisth says it's unable to authenticate despite the same keys working in other clients (like the default Terminal.app on the Mac or Termius).

My server's auth.log looks like this (with `LogLevel = DEBUG3` in `sshd_config`):

    Connection from {iPhone} port 57856 on {Server} port 212
    Jan 29 18:44:50 server sshd[3505]: Failed unknown for {User} from {iPhone} port 57856 ssh2
    Jan 29 18:44:50 server sshd[3505]: user {User} login class  [preauth]
    Jan 29 18:44:50 server sshd[3505]: Failed unknown for {User} from {iPhone} port 57856 ssh2
    Jan 29 18:44:50 server sshd[3505]: user {User} login class  [preauth]
    Jan 29 18:44:50 server sshd[3505]: Accepted key ED25519 {Public key} found at /home/{User}/.ssh/authorized_keys:6
    Jan 29 18:44:50 server sshd[3505]: Postponed publickey for {User} from {iPhone} port 57856 ssh2 [preauth]
    Jan 29 18:45:00 server sshd[3505]: Connection closed by authenticating user {User} {iPhone} port 57856 [preauth]

As you can see, it tries two invalid login methods, then the public key is accepted, but it disconnects anyway.
