### ISSUE TITLE
duration issue/suggestion/question

### ISSUE THREAD

**Issue by jimlynnjulian** [ColdGrub1384/Pisth#4]
Hello,
   Perhaps more of a question/suggestion. 
   I've been using Pisth to replace my other SSH apps since I discovered Pisth some time ago.
   My issue concerns the duration of the app when idle. I use the app to control the linear actuator that positions a solar array. When troubleshooting or collecting data, I may leave the app idle for up to a minute. Everytime I leave the app idle, I have to restart the command line window again and re-enter the python code to control the array. 
   Is there a switch/option to allow a longer or unlimited delay between app actions.

**Comment by ColdGrub1384** [comment]
Hello,
Do the sessions stop immediately after suspending the app or after some time? The app is killed or only the session are stopped?

**Comment by jimlynnjulian** [comment]
Hello,

   Thanks for responding.
   Here's a description of the process.

I open the app and select the Raspberry Pi computer address.

A window opens with folders on the destination site.

I click the icon for a command line session. 

I run an operations script and examine the solar array or motor. In most cases, I run a Python script that takes Seconds and Direction as input. I position the array by running the actuator motor.

If I take a minute to examine the array, the command line session will auto-terminate and I will see the folders that were visible at the beginning of the session.

I have to click the command line icon again to reopen a command line window and type in the commands to run the actuator script again.

Jim Julian

**Comment by jimlynnjulian** [comment]
A correction:
When I return to my iPhone and the app, the screen is frozen and selecting the back arrow returns to the window with fokdrrs, sftp.

I place the phone in my pocket while I examine the array. 

I am aware my leg touch can trigger actions on the phone when I wear certain kinds of fabric.

**Comment by ColdGrub1384** [comment]
Thank you, I will try to fix it.

**Comment by ColdGrub1384** [comment]
Hello, I think I found the bug, and it's easy to fix it, but I'm not 100% sure if it's that. For testing, I created a script that prints text each second for 1 minute. When I run the script in background and I return to my phone, the terminal seems to not print text anymore but the script finished running. It looks like a freeze, but if I scroll down, I can see the command prompt. Can you please tell me if you can scroll and keep typing text?

**Comment by ColdGrub1384** [comment]
Ok, thank you. I fixed the bug and a new update will be available very soon. be111c9
