### ISSUE TITLE
Crash when opening a connection?

### ISSUE THREAD

**Issue by ColdGrub1384** [ColdGrub1384/Pisth#7]
Hello users! I received this review from the App Store:

> When I open a connection, it usually crashes.  On occasion it works, though.  It won’t remember SSH keys from sources other than its own folder, and it took me hours to figure that out.  It doesn’t give any specific errors; it just fails to authenticate.

> Great idea, but it simply doesn’t work well.  It’s not reliable enough for real use.

>iOS 12.1, iPad Pro 11 2018

I don't understand very well the review, I replied with that:

>Thanks for the review. It shouldn't crash when opening a connection, this is strange. For SSH keys, I don't know exactly what do you mean, when importing an SSH key, the key content is saved, so the file can be deleted. And for authentication error, maybe you filled the "Password" field with the user password, and it should be the private key passphrase.

I think I can understand the SSH keys issue, but for the crash...

I received 2 crash logs for images, when opening an image, it crashed and I fixed that in next update.

But. I haven't received nothing when opening a connection. I see some crashes on App Store Connect, but I don't have crash logs about connections...

Pisth doesn't crash when opening a connection for me.

So, I want to ask you, does Pisth crash sometimes when you open a connection? 

Please enable crash logs sharing with developers because it help us to fix bugs.

It would be strange if it's a thread issue, it crashed for that some versions ago, but I fixed it and I haven't received any crash log for that anymore. It should be very easy to debug it with crash logs.

Based on the username, I think it's maybe you, @KertDawg, that written the review. If it's you, please give more information here, if not, sorry :).

**Comment by KertDawg** [comment]
Hello.

There are two issues with the application.

1. I cannot import SSH keys from OneDrive or Drop Box.  When I attempt this
by importing the private key, entering the password, then saving, the key
is not used.  I look at the server logs and no key is being used.  If I
copy the file to the Pisth file area, then import that same key from the
Pisth file area, then it uses the key as evidenced by the server logs.
Something is different between local files and OneDrive/Drop Box.

2. When I open a connection to one of a few Linux OpenSSH servers, it
authenticates me, and then the app disappears.  There is no error message.
It succeeds occasionally, but not very often.

Thanks.

 - Kert

**Comment by ColdGrub1384** [comment]
Ok, thank you. I will try to fix the bug
