### ISSUE TITLE
App Store Author?

### ISSUE THREAD

**Issue by dschult** [ColdGrub1384/Pisth#8]
This program is available in the iOS App Store with the author name Marcela Cid.
I just want to know whether Marcela Cid is connected with @ColdGrub1384  in some way so that my purchase will support this development.

Also, is there a way to install this program without the App Store?  Do I have to become an Apple Developer?

**Comment by ColdGrub1384** [comment]
There are some other apps like "FoodKravings", "Afrimall Shopping" or "Collect The Trash!" that I made for clients on the App Store Account. But all apps under Marcela Cid developer account are coded by me except "Collect The Trash!" that I published for a friend.

**Comment by dschult** [comment]
Great!   Thanks for the info!  Congrats on publishing quality work...

**Comment by ColdGrub1384** [comment]
Thank you!
